uint64                      object_id
string                      class_string
bool                        estimate_attributes
bool                        estimate_states
sensor_msgs/Image           image
---
situated_hri_interfaces/CategoricalDistribution[]   attributes
situated_hri_interfaces/CategoricalDistribution[]   states